### ISSUE TITLE
Question: “No such file or directory: 'hhsearch'” when use "--template"

### ISSUE THREAD

**Issue by Tttgb** [YoshitakaMo/localcolabfold#172]
**What is your installation issue?**
I've installed localcolabfold without any problems, but when I run the multimer example, once I use "--template" I will get an error : "No such file or directory: 'hhsearch '" 

**Computational environment**

 - OS: [Ubuntu 20.04.6 LTS in Windows10 WSL2]
 - CUDA version if Linux :
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

**To Reproduce**
/mnt/f/Colabfold$ colabfold_batch ./test/testt.fasta ./test/ --model-type alphafold2_multimer_v3 --template --overwrite-existing-results
2023-08-29 10:34:13,485 Running colabfold 1.5.2 (33ae16f350b107cbec3523cdac363ddaae8497ec)
2023-08-29 10:34:14.564510: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-08-29 10:34:14,568 WARNING: no GPU detected, will be using CPU
2023-08-29 10:34:35.110746: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-08-29 10:35:00,358 Found 7 citations for tools or databases
2023-08-29 10:35:00,358 Query 1/1: 1BJP_homohexamer (length 372)
2023-08-29 10:35:09,616 Could not get MSA/templates for 1BJP_homohexamer: [Errno 2] No such file or directory: 'hhsearch'
Traceback (most recent call last):
  File "/mnt/f/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1377, in run
    = get_msa_and_templates(jobname, query_sequence, a3m_lines, result_dir, msa_mode, use_templates,
  File "/mnt/f/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 784, in get_msa_and_templates
    template_feature = mk_template(
  File "/mnt/f/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 130, in mk_template
    hhsearch_result = hhsearch_pdb70_runner.query(a3m_lines)
  File "/mnt/f/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/data/tools/hhsearch.py", line 86, in query
    process = subprocess.Popen(
  File "/mnt/f/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/mnt/f/Colabfold/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hhsearch'
2023-08-29 10:35:09,631 Done

**input sequence**
>1BJP_homohexamer
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR:
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR:
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR:
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR:
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR:
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR

Thanks!

**Comment by Tttgb** [comment]
Hi all, this seems to be a problem with hhsearch, after I reinstalled hhsearch the problem was solved
`conda activate /mnt/f/Colabfold/localcolabfold/colabfold-conda`
`conda install -c conda-forge -c bioconda hhsuite`

**Comment by dpretorius** [comment]
I am still getting the same error (shown below) even after reinstalling hhsearch:

2023-09-13 12:36:03,567 Running colabfold 1.3.0 (2a47c6f1459fbbdb5242cbc62173f9b513813cfa)
2023-09-13 12:36:15,566 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
2023-09-13 12:37:04,506 Found 4 citations for tools or databases
2023-09-13 12:37:09,518 Query 1/1: X (length 370)
2023-09-13 12:37:10,405 Sleeping for 5s. Reason: PENDING
2023-09-13 12:37:21,115 Could not get MSA/templates for X: [Errno 2] No such file or directory: 'hhsearch'
Traceback (most recent call last):
  File "/rds/general/user/dp5117/home/anaconda3/lib/python3.9/site-packages/colabfold/batch.py", line 1328, in run
    ) = get_msa_and_templates(
  File "/rds/general/user/dp5117/home/anaconda3/lib/python3.9/site-packages/colabfold/batch.py", line 787, in get_msa_and_templates
    template_feature = mk_template(
  File "/rds/general/user/dp5117/home/anaconda3/lib/python3.9/site-packages/colabfold/batch.py", line 165, in mk_template
    hhsearch_result = hhsearch_pdb70_runner.query(a3m_lines)
  File "/rds/general/user/dp5117/home/anaconda3/lib/python3.9/site-packages/alphafold/data/tools/hhsearch.py", line 86, in query
    process = subprocess.Popen(
  File "/rds/general/user/dp5117/home/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/rds/general/user/dp5117/home/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hhsearch'
2023-09-13 12:37:21,160 Done

**Comment by yanyang9705** [comment]
I cannot solve this problem by reinstalling the packages either.

**Comment by yanyang9705** [comment]
> I cannot solve this problem by reinstalling the packages either.

I just solved this problem by mannually activating the colabfold-conda environment even though i have exported the colabfold-conda/bin to the PATH. 

conda activate XXXXX/localcolabfold/colabfold-conda
