### ISSUE TITLE
GPU not recognized

### ISSUE THREAD

**Issue by helgepat** [YoshitakaMo/localcolabfold#209]
Hi,

I just installed localcolabfold on two of our workstations and in both cases it does not recognize the GPUs, is there something simple that I am missing?

`WARNING: no GPU detected, will be using CPU`

We routinely use these machines for other GPU computing tasks, so I assume they are set up correctly.

I noticed this error message (during install on the first machine, for the second I did not look):

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-cpu 2.15.0.post1 requires ml-dtypes~=0.2.0, but you have ml-dtypes 0.3.2 which is incompatible.`

First machine:

20.04.1-Ubuntu

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

gcc --version
gcc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

nvidia-smi 
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|   0  NVIDIA GeForce GTX 1080 Ti     On  | 00000000:03:00.0 Off |                  N/A |
|   1  NVIDIA GeForce GTX 1080 Ti     On  | 00000000:81:00.0 Off |                  N/A |

Second machine:

22.04.1-Ubuntu

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

nvidia-smi
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:41:00.0 Off |                  Off |
|   1  NVIDIA GeForce RTX 4090        On  | 00000000:42:00.0 Off |                  Off |

**Comment by YoshitakaMo** [comment]
Unfortunately, this issue did not occur in my environment. I installed the latest version freshly today. My environments are here:
OS: Rocky Linux 8.8 and Ubuntu 22.04.3
GCC: 12.2.0
CUDA: 12.1.1

Please check the following points.

1. Does `nvidia-smi` work properly? This is mandatory.
1. Reboot the machine.
1. Install using the latest `install_colabbatch_linux.sh` in another directory.
1. Check whether jax can recognize the device:

```python
$ /path/to/your/localcolabfold/colabfold-conda/bin/python3.10
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0] on linux
>>> import jax
>>> print(jax.local_devices()[0].platform)
gpu
```
I expect "gpu" returns here.

**Comment by helgepat** [comment]
Hi,

I already tried rebooting and did not have other environments active (just to check: I do not have to manually activate the environment before running localcolabfold?)

I ran the python commands you stated and there is indeed an error message:

`>>> print(jax.local_devices()[0].platform)
CUDA backend failed to initialize: Found CUDA version 11070, but JAX was built against version 11080, which is newer. The copy of CUDA that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
cpu`

**Comment by YoshitakaMo** [comment]
This message seems that the installed jax and jaxlib are not compatible with your machine environment. Your `nvcc --version` returns 11.8, which satisfies the requirement. However, `Found CUDA version 11070` means you have CUDA 11.7 and the machines tried to use cuda 11.7 libraries. This mismatch may cause this problem.
Check your environment variable `LD_LIBRARY_PATH` correctly returns `/usr/local/cuda-11.8/lib64` or later version when the localcolabfold runs.

In my environment:
```bash
$ echo $LD_LIBRARY_PATH
/usr/local/cuda-11.8/lib64:/usr/local/cuda/lib64 # cuda 11.8
/usr/local/cuda-12.1/lib64:/usr/local/cuda/lib64 # cuda 12.1
```

Note that if multiple environment variables are present, they are prioritized in order from the left.

**Comment by helgepat** [comment]
Hi,

My `LD_LIBRARY_PATH` is empty and I installed CUDA 11.8 from the Nvidia repository, there is no other version of CUDA installed `ls /usr/local/`
 `bin  cuda  cuda-11  cuda-11.8  etc  games  include  lib  man  phenix-1.19.2-4158  sbin  share  src`

**Comment by YoshitakaMo** [comment]
Hm, I'd like to know your jaxlib version. In my environment, I used jaxlib 0.4.23+cuda11.cudnn86.

```bash
$ COLABFOLDDIR="/path/to/your/localcolabfold"
$ "$COLABFOLDDIR/colabfold-conda/bin/pip" list | grep "jaxlib"
jaxlib                       0.4.23+cuda11.cudnn86
```

The issue may be solved by installing another jaxlib-whl file built with an older cuda version. To install it, for example,

```bash
# uninstall current jaxlib
"$COLABFOLDDIR/colabfold-conda/bin/pip" uninstall jaxlib -y
# install another version, jaxlib 0.4.7+cuda11.cudnn82 for python3.10
"$COLABFOLDDIR/colabfold-conda/bin/pip" install https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.4.7+cuda11.cudnn82-cp310-cp310-manylinux2014_x86_64.whl
```

Then, check `print(jax.local_devices()[0].platform)` result.

**Comment by helgepat** [comment]
I succesfully installed the new jaxlib, but now running `import jax` throws an error

`>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/__init__.py", line 39, in <module>
    from jax import config as _config_module
  File "/path/to/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/config.py", line 15, in <module>
    from jax._src.config import config as _deprecated_config  # noqa: F401
  File "/path/to/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/config.py", line 28, in <module>
    from jax._src import lib
  File "/path/to/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 74, in <module>
    version = check_jaxlib_version(
  File "/path/to/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 63, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.4.7, but this version of jax requires version >= 0.4.19.
`

**Comment by YoshitakaMo** [comment]
Sorry, I forgot to tell you that `jax==0.4.7` is also required.
"$COLABFOLDDIR/colabfold-conda/bin/pip" uninstall jaxlib -y

**Comment by helgepat** [comment]
That did the trick! It is now recognizing the GPUs, thank you for your suggestions!
