### ISSUE TITLE
Exceeded memory limit issue on linux server

### ISSUE THREAD

**Issue by isdesta** [YoshitakaMo/localcolabfold#27]
When I run the colabfold executable on linux server (with slurm job scheduler) after installing without any glitches, I get the following output on the output file eventhough I request for nearly 12gigs of memory on the sbatch script. 

2021-10-27 13:15:35.963528: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-10-27 13:15:42.473577: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-10-27 13:15:43.476249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:05:00.0 name: Tesla K20m computeCapability: 3.5
coreClock: 0.7055GHz coreCount: 13 deviceMemorySize: 4.63GiB deviceMemoryBandwidth: 193.71GiB/s
2021-10-27 13:15:43.476936: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-10-27 13:15:43.568309: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-10-27 13:15:43.568439: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-10-27 13:15:43.604743: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-10-27 13:15:43.628756: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-10-27 13:15:43.695103: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-10-27 13:15:43.740556: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-10-27 13:15:43.747635: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-10-27 13:15:43.758695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-10-27 13:15:54.287682: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 19897253888 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2021-10-27 13:15:54.287770: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 17907527680 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2021-10-27 13:15:54.287798: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 16116774912 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2021-10-27 13:15:54.287818: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 14505097216 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2021-10-27 13:15:54.287838: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 13054586880 bytes unified memory; result: CUDA_ERROR_INVALID_VALUE: invalid argument
2021-10-27 13:15:55.703597: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 11749128192 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:15:57.518297: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 10574215168 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:15:59.337052: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 9516793856 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:01.129516: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 8565114368 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:02.945864: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 7708602880 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:04.760092: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 6937742336 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:06.572127: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 6243968000 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:08.382901: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 5619571200 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:10.195180: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 5057613824 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:12.005831: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 4551852544 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:13.820047: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 4096667136 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:15.632651: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 3687000320 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:17.445155: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 3318300160 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:19.252805: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 2986470144 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:21.063185: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:764] failed to alloc 2687823104 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-10-27 13:16:28.041902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-10-27 13:16:28.041959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]
2021-10-27 13:16:28.140439: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1999895000 Hz
slurmstepd: error: Job 39188705 exceeded memory limit (1253252 > 1024000), being killed
slurmstepd: error: *** JOB 39188705 ON node101 CANCELLED AT 2021-10-27T13:16:35 ***

**Comment by isdesta** [comment]
I actually re-installed it and ran it with the XLA_FLAGS command (after my #sbatch directives) and it worked fine. So, 
export XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1 works!
