### ISSUE TITLE
ERROR: Jax could not find GPU. This can be either because your machine doesn't have a GPU

### ISSUE THREAD

**Issue by WHEREISSHE** [YoshitakaMo/localcolabfold#85]
When I run`nvcc --version`,  the output seems well:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```
But when I tried to run it, something went wrong:
```
2022-06-04 18:29:41,645 Running colabfold 1.3.0 (e3b219cc10e6165f424789ec754ff8da7dbecbbf)
2022-06-04 18:29:52.068215: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
ERROR: Jax could not find GPU. This can be either because your machine doesn't have a GPU
or because jax can't find it. You might need to run

pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html  # Note: wheels only available on linux.

See https://github.com/google/jax/#pip-installation-gpu-cuda for more details.

If you're sure you want to run without a GPU, pass `--cpu`
```
Is it caused by `Cuda compiler` version conflict or other reasons? If there is any way to fix it, I will be appreciated.

**Comment by YoshitakaMo** [comment]
Has this problem been resolved? Not only `nvcc --version` check but `nvidia-smi` to check whether the machine can communicate with GPU is needed. In my case, it was resolved after rebooting the machine.

**Comment by WHEREISSHE** [comment]
The error is still occured on my own machine, perhaps I should get it reinstalled. Besides I also tried to run this on another computer, it worked. It's amazing and thank you!
